### ISSUE TITLE
Snbt lists, arrays, compoumds support for versions 1.12.2 and below

### ISSUE THREAD

**Issue by semayellow** [peunsu/ftb-snbt-lib#21]
Hi!

Could u add supporting for earlier versions for lists, arrays and compounds with separating elements by commas.
This can be implemented as an additional funcion or class constructor parameter.

Im writing a script to export quests from betterquesting 1.7.10 to ftb quests 1.12.2 and higher. 
So, I was forced to write my own parser to separate list elements with commas working with ftb on version 1.12.2

I tried using several other snbt libraries from PyPI with this feature, but they were all written terribly.

**Comment by peunsu** [comment]
I am going to work on it :D

**Comment by peunsu** [comment]
Now supports writing ``snbt`` files with comma separators. (#22)
Please let me know if there are any issues with this update.
Thank you :)

**Comment by semayellow** [comment]
Thank u very much! I will check it
